function gs1th = gs1func(in1)
%GS1FUNC
%    GS1TH = GS1FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
gs1th = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,th1,0.0,0.0,1.0],[4,4]);
