function gs2th = gs2func(in1)
%GS2FUNC
%    GS2TH = GS2FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
th2 = in1(2,:);
gs2th = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,th1,th2,0.0,1.0],[4,4]);
