function gs3th = gs3func(in1)
%GS3FUNC
%    GS3TH = GS3FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
gs3th = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,th1,th2,th3,1.0],[4,4]);
