function gs4th = gs4func(in1)
%GS4FUNC
%    GS4TH = GS4FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
t2 = cos(th4);
t3 = sin(th4);
gs4th = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(-1.0./2.0e1)+th1,t3.*(-1.0./2.0e1)+th2,th3+3.0./2.0e1,1.0],[4,4]);
