function gs5th = gs5func(in1)
%GS5FUNC
%    GS5TH = GS5FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
t2 = sin(th4);
t3 = cos(th4);
t4 = cos(th5);
t5 = sin(th5);
gs5th = reshape([t3,t2,0.0,0.0,-t2.*t4,t3.*t4,-t5,0.0,-t2.*t5,t3.*t5,t4,0.0,t3.*(1.0./2.0e1)+th1-t2.*t4.*(1.0./4.0),t2.*(1.0./2.0e1)+th2+t3.*t4.*(1.0./4.0),t5.*(-1.0./4.0)+th3+3.0./1.0e1,1.0],[4,4]);
