function gs6th = gs6func(in1)
%GS6FUNC
%    GS6TH = GS6FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 12:26:44

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
th6 = in1(6,:);
t2 = th5+th6;
t3 = sin(th4);
t4 = cos(th4);
t5 = cos(th5);
t6 = cos(t2);
t7 = sin(t2);
t8 = sin(th5);
t9 = sin(th6);
t10 = cos(th6);
gs6th = reshape([t4,t3,0.0,0.0,-t3.*t6,t4.*t6,-t7,0.0,-t3.*t7,t4.*t7,t6,0.0,t4.*(1.0./2.0e1)+th1-t3.*t5.*(1.0./2.0)-t3.*t5.*t10.*(1.0./4.0)+t3.*t8.*t9.*(1.0./4.0),t3.*(1.0./2.0e1)+th2+t4.*t5.*(1.0./2.0)+t4.*t5.*t10.*(1.0./4.0)-t4.*t8.*t9.*(1.0./4.0),t7.*(-1.0./4.0)-t8.*(1.0./2.0)+th3+3.0./1.0e1,1.0],[4,4]);
